ereadingtool/ereadingtool

text/static/text/css/text.css
text/static/text/js/text.js
text/ui/text.elm
text/ui/textreader/model.elm
text/ui/textreader/msg.elm
text/ui/textreader/view.elm

* Add a ToggleGloss message so that you can select/de-select a word
for glossing.
* Improve CSS naming conventions using hyphens rather than underscore

* Text Reader UI

---

text/static/text/js/text.js
text/static/text/js/text_search.js
text/ui/textreader/textword.elm
text/ui/textreader/view.elm

* Don't show words with no translations defined by the instructor for
for glossing.

Fix to correct merged words missing from the list of defined text words.

---

ereadingtool/static/css/ereader_unauth.css
ereadingtool/templates/about.html

* Per Bill, left-align the text while keeping the images centered.

Updates about page tutorial.

---

instructor_admin/static/admin/js/create_text.js
instructor_admin/ui/text/translations/model.elm
instructor_admin/ui/text/translations/view.elm
text/translations/group/models.py
text/views/api/text_word/group.py

* Update to OrderedDict to accurately keep track of merge order
*face palm*
* Add __str__() method for TextGroupWord
* Cleanup imports

Fix merging words bug.

---

flashcards/session/base.py

* Remove check for deleted sessions, which is a holdover from when
before we knew we wanted to keep a record of multiple sessions.

Fix flashcards

---

flashcards/static/flashcards/js/flashcards.js
instructor_admin/static/admin/js/admin.js
instructor_admin/static/admin/js/create_text.js
tests/Test/User/Instructor/Profile.elm
text/static/text/js/text.js
text/static/text/js/text_search.js
user/instructor/models.py
user/static/user/js/forgot_password.js
user/static/user/js/instructor_login.js
user/static/user/js/instructor_profile.js
user/static/user/js/instructor_signup.js
user/static/user/js/password_reset_confirm.js
user/static/user/js/student_login.js
user/static/user/js/student_profile.js
user/static/user/js/student_signup.js
user/static/user/js/view.js
user/ui/instructor/instructor_profile.elm
user/ui/instructor/profile.elm
user/ui/instructor/profile/flags.elm
user/ui/instructor/profile/init.elm
user/ui/instructor/profile/model.elm
user/ui/instructor/profile/msg.elm
user/ui/instructor/profile/view.elm
user/views/instructor.py

when there are no current invites.  Fixes issue #14:
* Add Test.User.Instructor.Profile functions for ensuring the proper
invite view
* Add `invites` and `instructor_admin` flags via the backend if the
user is an admin user
* Split up instructor profile app into separate modules
* Clean up some imports in the instructor views

Fix case where admin instructor does not get the proper invite view

---

text/tests.py
text/translations/tests.py

* Fix broken tests for translations.
* Add skipIf decorator for unit tests requiring redis
(could be added later)

Add continuous integration to ereader project.

---

user/views/forgot_password.py

Fix wrong url being sent for forgot password form.

---

flashcards/tests.py

Fixes the wrong year in a flashcard test.

Fix wrong year in flashcard test

---

ereadingtool/test/site.py

This is part of the work for issue #51 .  There is a Django/SQLite bug that prevent us from properly using Django LiveServerTestCase at the moment, so this is the workaround I came up with.

Adds a basic selenium test for the student profile page.

---

ereadingtool/test/site.py
test_cleanup.zsh
user/static/user/js/forgot_password.js
user/static/user/js/instructor_login.js
user/static/user/js/instructor_profile.js
user/static/user/js/instructor_signup.js
user/static/user/js/password_reset_confirm.js
user/static/user/js/profile.js
user/static/user/js/student_login.js
user/static/user/js/student_profile.js
user/static/user/js/student_signup.js
user/static/user/js/view.js
user/ui/student/profile/decode.elm

Simplified the Elm decoder decoding the student profile on the profile page.  Fixes issue #51 .

Fix issue #51 - Difficulty select doesnt refresh description

---

user/ui/Student/Performance/Report.elm
user/ui/Student/Profile.elm
user/ui/Student/Profile/Decode.elm
user/ui/Student/Profile/Encode.elm
user/ui/Student/Profile/Flags.elm
user/ui/Student/Profile/Help.elm
user/ui/Student/Profile/Model.elm
user/ui/Student/Profile/Resource.elm
user/ui/Student/Profile/Update.elm
user/ui/Student/Profile/View.elm
user/ui/Student/Resource.elm
user/ui/Student/Student_Login.elm
user/ui/Student/Student_Profile.elm
user/ui/Student/Student_Signup.elm
user/ui/Student/View.elm

This PR fixes shadowing errors, restricts module exports, removes unused locals and imports, and includes a few linting cleanups. The linting cleanups are in 034cbb1.

Upgrade student user directory

---

instructor_admin/static/css/ereader.css
text/static/text/css/text.css
text/static/text/css/text_search.css
text/ui/TextReader/View.elm

This PR updates the styling of buttons. It changes to color of buttons to the medium blue that we will eventually use in the header. It adds hover effects to buttons and tags and a blue hover outline to answers.
A small change was also made to properly style the buttons on the last page of texts.
Instructor-only buttons and other UI elements were not changed.
Closes #44. 
Closes #45.

Button enhancements

---

user/ui/Instructor/Instructor_Login.elm
user/ui/Instructor/Instructor_Profile.elm
user/ui/Instructor/Instructor_Signup.elm
user/ui/Instructor/Invite.elm
user/ui/Instructor/Invite/Decode.elm
user/ui/Instructor/Invite/Encode.elm
user/ui/Instructor/Profile.elm
user/ui/Instructor/Profile/Init.elm
user/ui/Instructor/Profile/View.elm
user/ui/Instructor/Resource.elm
user/ui/Instructor/View.elm

This PR fixes shadowing errors, restricts module exports, removes unused locals and imports, and includes a few linting cleanups. The linting cleanups are in b54cdfa.

Upgrade instructor user directory

---

text/static/text/js/text.js
user/static/user/js/profile.js
user/static/user/js/student_profile.js
user/static/user/js/view.js
user/ui/Student/Profile/View.elm

Removes a trailing slash to correct the link.

Fix broken STAR-Russian link

---

flashcards/static/flashcards/js/flashcards.js
flashcards/ui/Flashcard/Update.elm
flashcards/ui/Flashcards.elm

Fixes
- Lingering compilation issues with websocket changes.
- Improper Json.Decode.Error handling.

Flashcard Elm UI fixes

---

elm.json
instructor_admin/static/admin/js/admin.js
instructor_admin/ui/Admin.elm
instructor_admin/ui/Admin/Text.elm
instructor_admin/ui/Create_Edit_Text.elm
text/ui/TextSearch.elm
ui/Date/Utils.elm
ui/Text/View.elm

Adds:
- More shadowing fixes
- Time and DateTime fixes
- Cleans up URL functions

Elm 0.19 upgrade to the instructor admin page

---

ereadingtool/settings.py
requirements.txt
web/src/Api.elm
web/src/Main.elm
web/src/index.ts

This PR adds CORS support and tweaks our main Elm auth POC.

Add CORS support.

---

web/src/Flashcard/Decode.elm
web/src/Flashcard/Encode.elm
web/src/Flashcard/Mode.elm
web/src/Flashcard/Model.elm
web/src/Flashcard/Msg.elm
web/src/Flashcard/Update.elm
web/src/Flashcard/View.elm
web/src/Flashcard/WebSocket.elm

Add flashcard modules to SPA directory.
Note that this doesn't complete #127  because the `Flashcards.elm` page still needs to be added. This last bit of work is blocked by #107 and #128 (i.e. authentication and a couple of imports).

Add flashcard modules

---

web/src/User/Login.elm
web/src/User/User.elm

Not a complete implementation. More some ideas about how it might work now that we have static routes from `elm-spa`.

Convert login page route flags to elm-spa routes

---

web/src/Api.elm

Update Http helpers to call through the Endpoint module.

Update HTTP wrappers

---

web/src/Pages/Login/Instructor.elm
web/src/Pages/Top.elm
web/src/User/Login.elm
web/src/index.ts

Adds a custom login endpoint for student and instructor roles. The role is determined by which login page is used.

Add custom auth endpoints to frontend

---

web/src/Api.elm
web/src/Pages/Text/Id_Int.elm

Adds jwt as a querystring on websocket endpoints.

Add jwt as a querystring on websocket endpoints

---

ereadingtool/test/user.py
ereadingtool/urls.py
requirements.txt
text/consumers/student.py
user/forms.py
user/test/instructor.py
user/views/api.py
user/views/instructor.py
user/views/student.py
web/src/Api/Endpoint.elm

Reverts ereadingtool/ereadingtool#175
Missing review

Revert "Instructor vs student auth"

---

web/src/Api.elm
web/src/Flashcard/Model.elm
web/src/Flashcard/Msg.elm
web/src/Flashcard/Update.elm
web/src/Flashcard/View.elm
web/src/Flashcard/WebSocket.elm
web/src/Pages/Flashcards/Student.elm
web/src/Shared.elm

This PR adds an initial implementation for the Flashcards page in the SPA. The page compiles and loads, but it does not display anything at the moment because the websocket connection fails.
To test this PR, log in as a student and select the "Practice Flashcards" link. Navigation should be possible and the browser tab will say "Practice Flashcards", but nothing will be displayed.

Add initial flashcards page

---

web/public/css/user.css
web/src/Pages/Profile/Student.elm

This PR fixes styles on the difficulty preference select that were overridden in the avalanche of CSS cascades. They should look the used to now.
(A bit of linter thrash here too.)

Add styles to difficulty preference select

---

user/views/student.py

Once the tests have been updated we can bring this PR in.

HTML to JSON

---

user/views/student_performance.py

Here we avoid one unnecessary DB hit and just check the request path against the JWT.

Cleaned up the code.

---

report/models.py

Made a change to order the fields in the table to match the frontend.
They were previously ordered arbitrarily, but now they're ordered
according to their `id` in the database.

Ordered fields descending difficulty

---

README.md

Small addition about email settings and getting SendGrid in/out of `sandbox_mode`.

Updating README on local development

---

web/public/css/text_search.css
web/src/Pages/Text/Search.elm

This PR adds a hard link to the demo text to make it easier to find. 
To test, log in as a student and enable hints in the student profile. Navigate to the text search page. A welcome message with the link is displayed at the top of the page.
Related to #73.

Make demo text easier to find

---

web/public/css/ereader.css
web/src/Shared.elm

This PR fixes uneven padding in public navbar, adds some space between logo and menu items, and increases speed of all transitions.
To test it, run the app and view as a mobile device using the devtools.

Small fixes to mobile navbar styles

---

Dockerfile.django
Dockerfile.node

updated the dockerfiles to pull from the new development branch

New branch

---

user/mixins/models.py

Over specified in the filter to the point of only focusing on student
records. Turns out that broke the instructor. Also, since self is
already that type (student or instructor) I don't think it was
necessary.
Branch name is misleading, bug came from the sections incomplete 
bug fix.

Sections incomplete field error

---

user/mixins/models.py

Accidentally left some code in and removed an unnecessary field that
caused the app to barf.

Cleaned up code and fixed last_read field bug

---

user/ui/Instructor/Profile/View.elm
web/src/Pages/Profile/Instructor.elm
web/src/User/Instructor/Profile/View.elm

updated the placeholder in the invite field to say "content editor"

instructor -> content editor

---

web/public/css/instructor_profile.css

Small PR to styles the link in the newly added text instructing Content Editors how to invite other Content Editors.

url now matching other styles

---

web/public/css/user_profile.css
web/src/Pages/Profile/Student.elm

This PR adds a banner above the student profile page when "Show Hints" is turned on. 
To test it, log into the site as a student, toggle "Show Hints" on. The banner should appear at the top of the page.

Add student welcome banner

---

report/templates/student_flashcards_report.html
report/templates/student_performance_report.html
user/views/student_flashcards.py
user/views/student_performance.py

Adding the username and the UTC timestamp to the files. Test this by downloading a performance report and a my words PDF file. Check the uppermost part of the document and there should be the username used by your STAR account along with a UTC timestamp DD/MM/YYYY

PDF files include meta information

---

web/public/css/ereader.css
web/src/Pages/Signup/Student.elm

Includes updated text according to shared Google Doc and styling for the
link.

Signup page contents

---

web/src/Pages/Profile/Student.elm

Difficulties updated to match the explanation on the student signup
page.

Updated difficulty text

---

web/src/Pages/Profile/Student.elm

Updated contact links which closes #396

Contact links

---

web/public/css/ereader.css

Needed to play with the CSS so images won't stretch incorrectly in Safari on Desktop and IOS.

Annoying Safari bug

---

web/public/css/ereader.css
web/public/css/instructor_profile.css

**What it does**
Styling fixes change the instructor's profile page and edit text page on a mobile device. 
**Things to test for:**
**Files this PR touches:**
Most CSS files
Some Elm files to add/change attributes (`"class"`, `"id"`)

Instructor profile page
