ereadingtool/ereadingtool

tests/Test/Text/Parse/CompoundWords.elm
text/models.py
text/static/text/js/text.js
text/translations/models.py
text/translations/tests.py
text/ui/textreader/view.elm
ui/text/section/words/tag.elm

* Add a passing elm test for compound words.
* Clean up some imports in Python and some redundant test code.
* Clean up function names in Elm and removed unnecessary parentheses.
* Remove filtering of words that do not have `correct_for_context=True`
definitions.  This was removing words that have recently
become part of a word group.

Fix to correct merged words missing from the list of defined text words.

---

text/translations/tests.py
text/views/api/text_word/group.py

* Fix not preserving parameter order properly by relying on
Django/SQLite query result order
* Add a regression test for the issue

Fix word group order on backend.

---

.gitignore
instructor_admin/ui/text/translations/word/instance/encode.elm

Found by Brian G. : fix .gitignore which took out Translation.Word.Instance.Encode from the Elm modules

Fix gitignore and add missing file

---

flashcards/static/flashcards/js/flashcards.js
instructor_admin/static/admin/js/admin.js
instructor_admin/static/admin/js/create_edit_text.js
instructor_admin/ui/text/translations.elm
instructor_admin/ui/text/translations/decode.elm
text/static/text/js/text.js
text/static/text/js/text_search.js
text/translations/models.py

Adds missing record field 'instance' for word grouping records.  I'm unaware of how this is not present in master when the last commit to that file shows the field as present.
I tested some example texts with grouping to confirm it is working.  This will only affect texts with grouped words.
You can use text id=9 to test some grouped words.  They are present in the first section.  'По данным' is one example.

Fix missing word group record field

---

.gitignore

Adds VSCode config directory to `.gitignore`.

Ignore VSCode config directory

---

ereadingtool/settings.py
ereadingtool/test/user.py
ereadingtool/urls.py
requirements.txt
text/views/api/text_sections.py
user/test/instructor.py
user/test/student.py

JWT Support  
- Adds a JWT auth middleware
- Adds a test for logging in with a username/password and hitting an endpoint with the proper authorization token
- Removes unused imports in text sections
- Adds URI routing for two new auth endpoints:
- /token-auth/
- /token-refresh/
JWT Auth Testing
- Removes some improper use of .example() with hypothesis strategies
- Refactors TestUser login method to use JWT
- Removes TestUserLogin class
- Fixes broken 'welcome message' test that wasn't logging in with the TestUser login

Add JWT Authentication Support

---

web/src/Pages/ProtectedApplicationTemplate.elm
web/src/Shared.elm
web/src/Spa/Page.elm

This PR adds a `protectedApplication` to `Page.elm`. `protectedApplication` checks if the user is logged in before loading the page. If the user is logged in, the page loads. Otherwise, they are redirected to the login page. (At the moment, the login page is `Top`. We will want to update this to the actual login page when we bring it in.)
In addition, `protectedApplication`'s `load` function will check on the session and navigate the user to login page if a logout occurs. This makes it possible to log users out in all browser tabs.
`ProtectedApplicationTemplate.elm` is an example `protectedApplication` and a template that we can use as a starting point for other protected pages. Note that we need to use a `SafeModel` that is wrapped by `Model` because `elm-spa` needs `Model` internally …

Add protected pages

---

web/elm.json
web/src/InstructorAdmin/Admin/Text.elm
web/src/InstructorAdmin/Text/Create.elm
web/src/InstructorAdmin/Text/Translations.elm
web/src/InstructorAdmin/Text/Translations/Decode.elm
web/src/InstructorAdmin/Text/Translations/Encode.elm
web/src/InstructorAdmin/Text/Translations/Model.elm
web/src/InstructorAdmin/Text/Translations/Msg.elm
web/src/InstructorAdmin/Text/Translations/Subscriptions.elm
web/src/InstructorAdmin/Text/Translations/TextWord.elm
web/src/InstructorAdmin/Text/Translations/Update.elm
web/src/InstructorAdmin/Text/Translations/View.elm
web/src/InstructorAdmin/Text/Translations/Word/Instance.elm
web/src/InstructorAdmin/Text/Translations/Word/Instance/Encode.elm
web/src/InstructorAdmin/Text/Translations/Word/Kind.elm

This PR moves the instructor admin modules into the SPA directory and renames modules and imports as needed. It also adds `y0hy0h/ordered-containers` back in as a dependency.
Note that this doesn't complete #129 because the `Admin.elm` and `Create_Edit_Text.elm` pages still need to be added. This last bit of work is blocked by #107, #126, and #128 (i.e. authentication and a few imports).

Move instructor admin modules into SPA

---

web/elm.json
web/src/TextReader.elm
web/src/TextReader/Answer/Decode.elm
web/src/TextReader/Answer/Model.elm
web/src/TextReader/Decode.elm
web/src/TextReader/Encode.elm
web/src/TextReader/Flashcard/Student.elm
web/src/TextReader/Model.elm
web/src/TextReader/Msg.elm
web/src/TextReader/Question/Decode.elm
web/src/TextReader/Question/Model.elm
web/src/TextReader/Section/Decode.elm
web/src/TextReader/Section/Model.elm
web/src/TextReader/Text/Decode.elm
web/src/TextReader/Text/Model.elm
web/src/TextReader/TextWord.elm
web/src/TextReader/Update.elm
web/src/TextReader/View.elm
web/src/TextReader/WebSocket.elm
web/src/TextSearch.elm
web/src/TextSearch/Help.elm

This PR moves the text modules from `text/ui/` into the SPA directory and renames imports as needed. It also adds `PanagiotisGeorgiadis/elm-datetime` and `waratuman/json-extra` back in as dependencies.
Note that this doesn't complete #126 because the `Text.elm` page still needs to be added. Adding this page is blocked by #107 and #128 (i.e. authentication and a few imports).

Add text modules

---

web/src/Api.elm

Adds replacements for the wrapper functions that we had in `HttpHelpers.elm`. There are a couple of changes in the way these wrappers will be used.
We have upgraded to `elm/http` v2.0.0, which means we no longer need to make a request which we later send. Instead, the new API creates commands directly without having to send them. In practice, this means we pass in the `Msg` constructor that handles the HTTP response and the wrapper function returns a `Cmd msg`. (see https://elm-lang.org/news/working-with-files#simplifying-elm-http-.)
We need to pass in `Maybe Cred` instead of a `List Http.Header` that contains a CSRF token. Now that we are using JWTs, we won't need the CSRF token, but we will need `Maybe Cred` to tell us whether the user is logged in or not. `Maybe Cred` is available by …

Add HTTP wrapper replacements for HttpHelpers

---

web/elm.json
web/public/css/text.css
web/public/css/text_search.css
web/src/Api/Endpoint.elm
web/src/InstructorAdmin/Admin/Text.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Text/Search.elm
web/src/Shared.elm
web/src/Text/Decode.elm
web/src/Text/Search.elm
web/src/Utils/Date.elm
web/src/index.html
web/tests/Tests/Date.elm

Adds text search page to the elm-spa implementation. The page uses a fake student profile for the moment.
Datetimes that come from the server are ISO8601, and we convert to POSIX time in the text and text list decoders.
The `Utils.Date` module has been refactored to fix a couple of bugs. The implementation does not localize, and we should open an issue to do that. A test suite to check string representations of datetimes has been added. 
The difficulties and reading statuses have been added to the `Shared` module. We may want to configure the app with these at app initialization.
The construction of `QueryParameter`s is not great in this implementation, but it will take a bit of refactoring to change the way this works. An issue should be opened on it.

Add text search page

---

ereadingtool/test/user.py
user/forms.py
user/test/instructor.py
user/test/student.py
user/views/api.py
user/views/instructor.py
user/views/student.py

Removes `/token-auth/` endpoint.
Makes 
`api/instructor/login/`
`api/student/login/`
into JWT auth endpoints returning customized JWT payloads.
This closes #147 .

Divide Django JWT auth endpoint per user type

---

user/views/student.py
web/public/css/user_profile.css
web/src/Api.elm
web/src/Api/Config.elm
web/src/Api/Endpoint.elm
web/src/Id.elm
web/src/Pages/Login/Instructor.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Text/Id_Int.elm
web/src/Pages/Text/Search.elm
web/src/Pages/Top.elm
web/src/Shared.elm
web/src/Spa/Page.elm
web/src/User/Profile.elm
web/src/User/Student/Profile.elm
web/src/User/Student/Profile/Decode.elm
web/src/User/Student/Profile/Help.elm
web/src/Viewer.elm
web/src/index.ts

This PR adds localstorage persistence for roles, ids, and a show help flag. It also includes a hot patch to get the backend serving partial student profiles.
The following should work now:
- When a student logs in, they are redirected to the profile page and parts of their profile will load (see #159 regarding some missing parts)
- If a student closes the browser and re-opens the app or opens the app in a new tab, they are redirected to their profile page and their profile loads (the persistence piece)
- A new show help button toggles help messages on and off and the student's preference is persisted across sessions
- A student is always shown help messages the first time they use the app

Add profiles and show help persistence

---

web/src/Api/Endpoint.elm
web/src/Pages/Profile/Instructor.elm
web/src/Shared.elm
web/src/User/Instructor/Profile.elm
web/src/User/Instructor/Resource.elm
web/src/User/Profile.elm

Add the initial implementation for the instructor profile page. See #163 for parts that have not been completed.
To test this page, login as an instructor and make check that you are redirected to the instructor profile page. You should see a placeholder username "fakeInstructor". 
The instructor profile page should also load on a page refresh or if opened in another tab.

Add instructor profile page

---

web/src/Pages/Profile/Instructor.elm
web/src/Pages/Text/EditorSearch.elm

This PR adds an editor search page where content creators (instructors) can search for texts to edit.
To test it out, log in as an instructor and click on the "Find a text to edit" link in the navbar. After a moment, the page should be populated with a list of texts.

Add editor search page

---

web/src/Api.elm
web/src/Pages/Login/Instructor.elm
web/src/Pages/Profile/Instructor.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Signup/Instructor.elm
web/src/Pages/Signup/Student.elm
web/src/Pages/Text/EditorSearch.elm
web/src/Pages/Text/Id_Int.elm
web/src/Pages/Text/Search.elm
web/src/Pages/Top.elm
web/src/Pages/User/ForgotPassword.elm
web/src/Pages/User/ResetPassword/Uidb64_String/Token_String.elm
web/src/Shared.elm

This PR moves the navbar from each individual page into the Shared module. The shared the implementation displays one of the following:
- An unauthenticated navbar
- A student navbar
- An instructor navbar
All links in each version of the navbar should route the to the appropriate page if implemented or the NotFound page if not.
A link was also added to the STAR logo directing the user to their profile or to the homepage if they are not authenticated. This addresses #46.

Move navbar to Shared module

---

ereadingtool/views.py
question/views.py
text/views/api/lock.py
text/views/api/tag.py
text/views/api/text.py
text/views/api/text_sections.py
text/views/api/text_word/group.py
text/views/api/text_word/word.py
text/views/api/translations.py
user/views/api.py
user/views/instructor.py
user/views/student.py

Previously CSRF-exemption was only added to certain login-related and user-related endpoints.  This extends the same exemption to the rest of the site's endpoints.
- Adds a base view for all API views
- Adds aforementioned base view as a base class for all class-based API views
I confirmed derived classes hit the `csrf_exempt` decorator but it is unclear whether the Django testing framework is able to test this properly with `Client(enforce_csrf_checks=True)`.   Closes #173.

Add CSRF-exemption to all ReST API endpoints

---

ereadingtool/test/user.py
user/forms.py
user/test/instructor.py
user/views/api.py
user/views/instructor.py
user/views/student.py
web/src/Api/Endpoint.elm

It'll be done earlier on in the application logic for allowing or denying a student access to the webapp. Students and instructors were previously allowed through `post_success` and then reverted to a `post_error` if it turned out they have a particular administrative attribute. Now the request path is checked against the user's DB entry to see if the `is_staff` flag is set.
Tests needed to be updated so that they'd work. Specifically, if an instructor is created by way of `new_user` (as they always are) the kwarg `is_staff=True` will be passed along.
Along with this change comes the resolution of issue #172, at least partially. Inheriting from `View` as opposed to `EreadingToolAPIView` gives us the ability to inherit the `method_decorator(csrf_exempt)` which will allow prevent CSRF token …

These changes will divide instructors and students

---

web/src/Shared.elm

This PR fixes a bug where all pages would redirect to the profile page on reload or when pasting a URL into the browser. It adds a list of public paths that should be redirected.
To test it out, log in as a student. Remove `/profile/student` from the URL in the URL bar and reload the page. The app should redirect you to the profile page. `/login/instructor`, `/signup/student`, and `/signup/instructor` should also redirect to the profile page, but authed pages that allow you to search or read a text should not redirect.
The same should be true when logged in as an instructor with the additional authed pages that an instructor has available to them.

Fix authed page redirects

---

web/public/css/text.css
web/src/Api.elm
web/src/Api/WebSocket.elm
web/src/Pages/Flashcards/Student.elm
web/src/Pages/Text/Id_Int.elm
web/src/Text/Section/Words/Tag.elm
web/src/TextReader/Question/Decode.elm
web/src/TextReader/Text/Decode.elm
web/src/index.ts

This PR adds most of the remaining functionality to the text reader page. It includes missing portions of UI, Elm 0.19 upgrades, a few styles that were broken by cascades, and an updated websocket implementation. All items checked in #157 should work.
In addition, a button was added to the text conclusion page to address #62. The text "Read Another Text" was used instead of "Find a text to read" because it is shorter and works better with the UI.

Add text reader and update websocket implementation

---

user/views/student.py

This PR address #186 in the following ways:
[x] The "is consenting to research endpoint" now supports the GET HTTP method and returns what you'd expect.
[x] "profile" now wraps the JSON blob from the PUT request as detailed in the aforementioned issue.
[x] We are now sending back the HTML which creates the table on the frontend.

Performance report data goes to frontend.

---

web/public/css/user_profile.css
web/src/Pages/Profile/Student.elm
web/src/Shared.elm
web/src/User/Profile.elm
web/src/User/Student/Performance/Report.elm
web/src/User/Student/Profile.elm
web/src/User/Student/Profile/Decode.elm

This PR implements a number of missing parts of the student profile page. All checked off items in #149 should work now. Note that we are holding off on flashcards and performance reports for now.
In addition to the changes listed there, a couple of other issues are addressed here:
- A heading that reads "Student Profile" was added above the student profile (#47)
- The link text for downloading performance report PDFs was updated (#52)

Add more to student profile page

---

user/views/student.py

Here I made a very simple change using the preexisting `.to_dict()` function for the `student`'s performance report. The I wrapped it in `json.dumps(..)`, piece of cake.

HTML to JSON for the performance report info

---

web/public/css/instructor_profile.css
web/src/Pages/Profile/Instructor.elm

This PR includes a couple of small fixes to the texts displayed in an instructor profile. Texts created by an instructor should be displayed as a list of cards. Each text should have a link to navigate to it.
The styling was updated a bit from the original styling to place the text below the other profile items. The list can get long and the styles were broken in these cases.

Fix broken link and broken styles

---

web/public/css/create_text.css
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Text/Section/View.elm
web/src/Text/Section/Words/Tag.elm
web/src/Text/Translations/View.elm
web/src/Text/View.elm
web/src/index.html

This PR adds missing functionality to the create and edit text pages and fixes a couple of issues:
- The translations should display when the Translations tab is selected and words can be selected to edit their translations (they cannot be edited yet, this will follow after #200)
- The styling in the page should match the production page more or less with a few minor improvements to the edit translations modal
- The text ID should display as a title in the browser tab

More work on create and edit text pages

---

web/src/Pages/Text/Edit/Id_Int.elm
web/src/Pages/Text/Id_Int.elm

This PR adds the text title or ID to the browser tab the the text reader and the text edit page. 
Note that we can add the title on the text edit page but not the text reader page at the moment. We could add the title to all websocket messages in the text reader to use the title there as well.

Add text title or ID to browser tabs

---

steps2ar.org

I needed to change the location block of this NGINX conf file because it
was stuck in a redirect loop. This takes all pages that don't exactly
match the $uri to the enterance of the webapp via /index.html

Change NGINX server

---

web/public/css/user.css
web/public/css/user_reset_pass.css
web/src/Pages/User/ResetPassword/Uidb64_String/Token_String.elm

This PR fixes inconsistent button heights on public pages and adds some padding to the reset password page. 
To test it out, inspect the application in a couple of mobile devices in landscape and portrait mode in the developer tools. The reset password page is at `user/reset-password/<UUID>/<token>`. No need to test the ability to reset a password, so fill in anything you like for `UUID` and `token`.

Styling fixes for mobile

---

web/src/Pages/Text/Search.elm

Updates the message when no questions have been attempted per #57.
To test, log in as a student and navigate to the text search page. Texts that you have not begun should say "None attempted" for questions correct as seen here:

Change questions attempted message for none

---

ereadingtool/settings.py
user/urls/forgot_pass.py

Adding this new setting results in debug mode being on or off dependent
on both the setting itself as well as the setting of `DEBUG` in
`settings.py`. Issue #239 details this more, but you must have both
`DEBUG=True` and `SENDGRID_SANDBOX_MODE_IN_DEBUG=True` for sandbox mode
to be enabled. This means no emails will actually be sent by SendGrid.
To turn off sandbox mode it's advised to simply set
`SENDGRID_SANDBOX_MODE_IN_DEBUG=False`.

New setting for sandbox emails

---

web/elm.json
web/src/Pages/Text/Create.elm
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Pages/Text/EditorSearch.elm
web/src/Pages/Text/Search.elm
web/src/Question/Decode.elm
web/src/Question/Model.elm
web/src/Shared.elm
web/src/Text/Decode.elm
web/src/Text/Model.elm
web/src/Text/View.elm
web/src/TextReader/Question/Decode.elm
web/src/TextReader/Question/Model.elm
web/src/TextReader/Text/Decode.elm
web/src/TextReader/Text/Model.elm
web/src/Utils/Date.elm
web/tests/Tests/Date.elm

This PR adds localization to dates and times shown in the text search and text editing pages.
To test it:
- Log in as a student and read a text. Go back to the text search page and check that your last read time is correct for your timezone.
- Log in as an instructor, create a new text and check that the time created is correct for your timezone. Open the editor search page and check that the created time is correct for the entry in the list of texts.

Localize datetimes

---

cors.conf

There's a file at the top level called cors.conf It's copy pasted onto
the reverse proxy via `volumes` in the docker-compose file. Adding
DELETE to this list should allow us to run DELETE http requests in the
few places in which they're done. Namely, deleting an entire text and
deleting the lock on editing a file.
Not sure how to test this PR on localhost. We won't get any CORS
conflicts until attempting to access resources from a subdomain.

DELETE header added to cors configuration

---

web/src/Pages/Text/Search.elm
web/src/Text/Search/Difficulty.elm

This PR changes the difficulty selection on the text search to only permit one option to be selected at a time. For reference, see #53. 
To test this PR, log in as a student and navigate to the text search page. Select a difficulty and verify it is the only one selected. Check that the texts displayed all match the selected difficulty. Repeat for each difficulty level. 
(Note that we have an ordering problem that should be addressed separately where the first request when landing on the page comes in after filtering. To test this one, wait until the initial search results come in, then test.)

Make text search difficulty selection mutually exclusive

---

user/views/api.py

Was overzealous in previous auth issues. They were likely covered by
`is_valid()` anyways. Just did away with all of the path checks. Further
more, there was no need to check `is_staff`. The purpose of that
database flag remains unclear.

Auth issue

---

web/src/Pages/Text/Id_Int.elm

Change button to say "Read Again" instead of "Start Over".
To test, log in as a student or instructor and read a text through to the end. Check that the button to start over says "Read Again".

Change restart text button copy

---

web/src/Pages/Text/Search.elm

This PR updates the text search page so that it brings in the student difficulty preference when they load the page from a link or refresh the page. The issue is that in those cases, we are loading their profile in Shared, but we weren't updating it in the text search page.
To test this, log in as a student, navigate to the text search page, and refresh the page. Your difficultly preference should update shortly after the page loads.

Update student difficulty preference from Shared

---

Dockerfile.django
docker-compose.yml

Previously we were copying the file onto the container from the VM.
That's silly, changes made to the DB on the container won't affect the
copy on the VM. Now the host shares the file with the container. This 
concludes the upgrade to containerization of the site. It was a bug, so
additional changes that aren't bug related should be filed as features.

DB persistence between starts and stops

---

web/src/User/Instructor/Profile.elm

This PR adds missing pieces from out optimize search changes. In particular, text `Text` type for instructor profiles expected fields that we removed. As a result, decoding failed and the instructor profile would not load.
To test this PR, log in as an instructor and make a text. Reload your profile and make sure the text is displayed.

Optimize search cleanup

---

web/package-lock.json
web/package.json
web/public/css/ereader.css
web/src/Infobar.elm
web/src/Pages/Profile/Instructor.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Text/Create.elm
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Pages/Text/Search.elm
web/src/Shared.elm
web/src/index.ts

This PR updates HTTP and WebSocket error handling to log the user out when their token has expired. In addition, a check has been added to make sure the user's JWT is valid on a return visit before logging them in automatically.
An infobar implementation has also been added to show user's a meaningful message when they are logged out automatically. The infobar displays auth error messages, such as when a user attempts to log in with the wrong credentials.

Add expired token handling to the frontend

---

web/public/css/ereader.css

This PR fixes a bug where the navbar was hidden, but its contents were still in the DOM. On some devices, users were unable to use the login form because of the hidden overhang.
To test this PR, open the app as a small mobile device in portrait mode in the developer tools. Inspect the elements in the `div` with the class `hidden-menu` and make check that have no height.

Fix hidden navbar overhang

---

web/src/Pages/Text/Id_Int.elm

This PR addresses the occasionally broken "Read Again" button in the text reader mentioned in #285. Sometimes, it would route the user to text 0 instead of the text they wished to start over. Likely, this was a race to get the ID from the text that sometimes got the ID of the default empty text instead.
To test this PR, read through a text and click Read Again to see if it starts you over. We will have to keep an eye on this one because it did not always happen, but hopefully this solves it.

Change read again to a link and take id from page

---

web/src/Pages/Text/Id_Int.elm
web/src/Text/Translations.elm
web/src/Text/Translations/Model.elm
web/src/Text/Translations/View.elm
web/src/Text/Translations/Word/Instance.elm
web/src/TextReader/TextWord.elm

This PR adds lemmas to the frontend. The lemmas are displayed in the text reader glosses and in the translations tab glosses as the main word form. The phrase is used as a fallback if the lemma is missing.
The lemma was also added to the grammemes dropdown as the first option, and it is saved when you save the other grammemes.
To test this PR, start off as an instructor and create a new text. Use the sample text "Это испытание". After the text is created, go to the translations tab on the edit page for the text. Add one of the words as a text word.  At this point, the displayed word should be the highlighted phrase. 
Log in as a student and find the text you just made. Check that the main displayed word matches the highlighted phrase.
Log back in as an instructor. Go to the edit page for …

Add lemmas

---

web/src/Shared.elm

Tiny PR to change the cursor to show a pointer when hovering over the logout link in the navbar. To test it, hover over "Logout" as a student and as an instructor.

Add pointer on hover over logout link

---

web/src/Api.elm
web/src/Api/WebSocket.elm
web/src/Pages/Flashcards/Student.elm
web/src/Pages/Profile/Instructor.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Text/Create.elm
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Pages/Text/EditorSearch.elm
web/src/Pages/Text/Search.elm
web/src/Shared.elm
web/src/index.ts

This PR adds a command to disconnect open websockets when we navigate to a new page. We don't have a teardown mechanism when we leave a page, so instead we clean up when we init the new page.
We are mainly doing this for the text reader websocket connection, but this implementation is more general because we may also need it for the flashcards websocket connection. 
To test this PR, start reading a text. Navigate to a new page from the navbar or at the end of the text by selecting "Read Again" or "Read Another Text".

Add close all websockets command

---

web/src/Pages/User/ForgotPassword.elm

When first navigating to the forgot password page, the button was not displayed correctly as a button. This PR fixes that.
To test, navigate to the forgot password button and check that the button looks like the buttons on the login pages.

Fix forgot password submit button styling

---

requirements.txt

PyJWT changed to 2.0.0 and the changes just rippled down to webstack.
Since they are no longer breaking `webstack-django-jwt-auth` and we'd
have to pin that too, we're going along with `latest` versions for
both.

PyJWT and webstack-django-jwt-auth

---

web/src/User/Login.elm

This PR adds `id`s to the email and password login form fields. The `id's are a target for clearing the inputs when we go between the student and instructor login pages.
To test, run the frontend. Enter an email and password and go to the instructor login page. The fields should clear. Then, do the same, but going from the instructor login page to the student login page.

Add ids to email and password inputs

---

web/src/Pages/Profile/Student.elm

This PR updates the student profile page to request an updated profile each time the page is visited. We want this to get the latest performance report stats to show the student.
To test this PR, log in as a student. Look at you performance report. Read a text you have not read before. Return to the student performance report page and check that your performance report stats have been updated.

Update student profile on profile page init

---

web/src/Text/Section/Words/Tag.elm
web/tests/Word/Tests.elm

This PR adds the em dash (U+2014) as valid trailing punctuation. To test it, open text 55 as a content creator and attempt to gloss phrases where the `—` character follows other instances of trailing punctuation.

Add em dash (U+2014) as trailing punctuation

---

web/public/css/ereader.css

The styling was overridden when we re-ordered CSS files in `index.html`.

Fix text search tag styling

---

text/models.py
text/views/api/text.py

These modifications allow us to add and delete questions from a text
section. Oddly enough adding a question failed when trying to access the
new question before it had been put in the database. There's no way it
could ever work, since it had yet to be validated in the first place.
There is some light verification of the data sent from the frontend.
Shortly after fixing the Add Question feature I realized that delete a
question doesn't work either. That was fixed by deleting all questions
from the text section and re-adding them from an existing copy (which
didn't include the ones to be deleted!).
To test these changes try the following, being sure to read the text
between each test.
* Add Question -> Save Text
* Delete Question -> Save Text
* Add Question -> Add Question -> Save Text
* …

Add and delete questions

---

web/public/css/create_text.css
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Question/View.elm
web/src/Text/Section/View.elm
web/src/index.ts

This PR stabilizes CKEditor by removing an unneeded initialization call, adds a white background to text inputs, and updates the label for deleting selected questions. It also does a small bit of clean up based on suggestions from the linter.
To test this PR, open a couple of texts as an editor and check that the introduction, conclusion, and source text sections initialize to show the right text, and you can click on them to edit text. Also, check that the other inputs have a white background and the label for deleting selected questions is updated to be plural (question -> questions).

Text editor improvements

---

user/urls/student.py
user/views/student_flashcards.py
web/public/css/user_profile.css
web/src/Api.elm
web/src/Api/Endpoint.elm
web/src/Pages/Profile/Student.elm
web/src/Pages/Text/Id_Int.elm

This PR makes the following changes:
- Rename "Flashcard words" to "My words"
- Update endpoints and downloads to download "words" instead of "flashcards"
- Swap the positions of my words and show hints sections in the student profile page
- Add styling to the update username controls
- Hide add and remove my words for instructors in the text reader
To test this PR, check the student profile to see that styling changes and the swap look good. Open a text as a student and check that the options for adding and removing words say "My Words" instead of "Flashcards" when glossing a word. Open a text as an instructor and check that you do not have an option to add to or remove from my words.

Student profile improvements

---

text/views/api/translations.py
web/src/Text/Translations/Model.elm
web/src/Text/Translations/Update.elm

Severing the potential to save merged words for now. We used to have an
error on the PUT endpoint since we were looking for a single/multiple
words attribute in TextPhrases that doesn't exist. We'll treat all words
hitting this endpoint as single for now.

Save for all working

---

NOTICE
web/public/css/ereader.css
web/public/css/user.css
web/public/img/info-black.svg
web/public/img/info-gray.svg
web/src/Pages/Signup/Student.elm
web/src/User/SignUp.elm

This PR adds an info toggle to the student signup page to show students information about the selected difficulty. It also reduces the width of the text on the sign up page to line it up with the form fields, and it fixes a bug where the show password eyeball was falling to the line below the password input on mobile.
To test, open the student signup page and click on the info icon. Try out each difficulty and check for the correct text. Check out the form on mobile and make sure things are generally looking good.

Add difficulty info to sign up page

---

web/src/Pages/Login/ContentCreator.elm
web/src/Pages/Login/Student.elm
web/src/Pages/NotFound.elm
web/src/Pages/Profile/ContentCreator.elm
web/src/Pages/Signup/ContentCreator.elm
web/src/Pages/Text/Create.elm
web/src/Pages/Text/CreatorSearch.elm
web/src/Pages/Text/Edit/Id_Int.elm
web/src/Shared.elm
web/src/Spa/Page.elm

This PR renames "instructor" in browser tab titles, links, text, and routes across the site. To test it, open all pages that a content creator might use and check that instructor has been replaced with content creator.

Rename instructor to content creator

---

text/ui/TextSearch.elm
web/src/Pages/Text/Search.elm

These changes make the difficulty more human readable in a text card on the search page.
"intermediate_mid" -> "Intermediate-Mid"
Was unable to see how this could be done without string comparison in the `case` statement.

Difficulty styling

---

web/.env.devel
web/.env.production

Hopefully updating these endpoints will prevent the Forgot Password
button from firing from one site while we're on another! Quite strange
behavior surrounding this bug.

Updating endpoints

---

web/public/css/homepage.css

Somewhere in our production build there is use of cssnano, which has a
bug that reduces opacity to 1% from whatever other setting. The fix to
this is either to use cssnano@nightly, or simply change the opacity to a
decimal rather than percentage. So it was converted to a decimal and the
problem has been averted.
https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/118

Opacity bugfix

---

web/public/css/ereader.css

Our new font makes the navbar links look to small. This PR ups the font size to make them reasonably sized again.

Navbar font size increase

---

web/public/css/ereader.css

PR brings in changes to the navbar on mobile devices. Rather than 225px, which scrunches things on mobile devices (we've got more in the navbar now), lets use 1fr! This splits the entries evenly.
Bringing this one in because it's styling and it's still Thursday.

Navbar on mobile

---

web/public/css/ereader-unauth.css
web/public/css/ereader.css
web/src/Help/Activities.elm
web/src/Pages/Guide/Comprehension.elm
web/src/Pages/Guide/Context.elm
web/src/Pages/Guide/GettingStarted.elm
web/src/Pages/Guide/Priority.elm
web/src/Pages/Guide/Progress.elm
web/src/Pages/Guide/ReadingTexts.elm
web/src/Pages/Guide/Settings.elm
web/src/Pages/Guide/Strategies.elm

Due to a diverging branch, there was a need to fork off master and copy all of the files into a single commit. The branch is named as such because the static page Recognition.elm needed to be deleted. Not to worry, they're mostly new files and some small additions to CSS. Devel seems to have gone out of sync at release 2.2.0
This commit brings in new student guide pages and makes some minor
styling adjustments. There are three subpages under the Strategies tab, each multiple choice questions. The contents of the pages have been combed through, but the functionality should still be confirmed. This could be tested is by sampling the multiple choice questions and trying each of the tabs at the top of the guide. The dev server is currently hosting the branch feature/guide-rewrite-no-recog so …

Updating Student Guide
